base:
 image: golang:1.6-wheezy
 volumes:
 - $PWD/app:/go/src/myapp
 working_dir: /go/src/myapp
 command: '/bin/bash -c "go get && go install && myapp"'

web:
 extends:
  service: base 
 ports:
 - "8000:8000"

tester:
 extends:
  service: base
 command: '/bin/bash -c "go get && go test -race -v"'

stress-web:
 extends:
  service: base
 command: '/bin/bash -c "go get && go install -race && myapp"'

stress-tester:
 extends:
  service: base
 volumes:
 - $PWD/app/client:/go/src/myapp
 links:
 - stress-web